name: 📦 Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish'
        required: true
        type: string
      dry_run:
        description: 'Dry run (do not actually publish)'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: |
            browser-tools-mcp/package-lock.json
            browser-tools-server/package-lock.json

      - name: 🔧 Install dependencies (MCP)
        run: |
          cd browser-tools-mcp
          npm ci

      - name: 🔧 Install dependencies (Server)
        run: |
          cd browser-tools-server
          npm ci

      - name: 🏗️ Build MCP Server
        run: |
          cd browser-tools-mcp
          npm run build

      - name: 🏗️ Build Browser Tools Server
        run: |
          cd browser-tools-server
          npm run build

      - name: 🧪 Test MCP Server
        run: |
          cd browser-tools-mcp
          # Basic smoke test
          node dist/mcp-server.js --help || echo "No help flag, that's ok"
          echo "✅ MCP Server builds and runs"

      - name: 🧪 Test Browser Tools Server
        run: |
          cd browser-tools-server
          # Basic smoke test - start server and stop after 5 seconds
          timeout 5s node dist/browser-connector.js || echo "Server started and stopped successfully"
          echo "✅ Browser Tools Server builds and runs"

      - name: 📋 Pre-publish Info
        run: |
          echo "## 📦 Publishing Information" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          cd browser-tools-mcp
          MCP_VERSION=$(node -p "require('./package.json').version")
          MCP_NAME=$(node -p "require('./package.json').name")
          echo "**MCP Package:** \`$MCP_NAME@$MCP_VERSION\`" >> $GITHUB_STEP_SUMMARY

          cd ../browser-tools-server
          SERVER_VERSION=$(node -p "require('./package.json').version")
          SERVER_NAME=$(node -p "require('./package.json').name")
          echo "**Server Package:** \`$SERVER_NAME@$SERVER_VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "🧪 **Mode:** Dry Run (no actual publishing)" >> $GITHUB_STEP_SUMMARY
          else
            echo "🚀 **Mode:** Live Publishing" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 📤 Publish MCP Server to NPM
        run: |
          cd browser-tools-mcp
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "🧪 Dry run: npm publish --dry-run"
            npm publish --dry-run
          else
            echo "🚀 Publishing to NPM..."
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY }}

      - name: 📤 Publish Server to NPM
        run: |
          cd browser-tools-server
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            echo "🧪 Dry run: npm publish --dry-run"
            npm publish --dry-run
          else
            echo "🚀 Publishing to NPM..."
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY }}

      - name: 🎉 Publish Summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 🎉 Publish Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ github.event.inputs.dry_run }}" != "true" ]; then
            cd browser-tools-mcp
            MCP_VERSION=$(node -p "require('./package.json').version")
            MCP_NAME=$(node -p "require('./package.json').name")

            cd ../browser-tools-server
            SERVER_VERSION=$(node -p "require('./package.json').version")
            SERVER_NAME=$(node -p "require('./package.json').name")

            echo "### 📦 Published Packages:" >> $GITHUB_STEP_SUMMARY
            echo "- [\`$MCP_NAME@$MCP_VERSION\`](https://www.npmjs.com/package/$MCP_NAME)" >> $GITHUB_STEP_SUMMARY
            echo "- [\`$SERVER_NAME@$SERVER_VERSION\`](https://www.npmjs.com/package/$SERVER_NAME)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🚀 Installation:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "# Install MCP Server" >> $GITHUB_STEP_SUMMARY
            echo "npx $MCP_NAME@$MCP_VERSION" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "# Install Browser Tools Server" >> $GITHUB_STEP_SUMMARY
            echo "npx $SERVER_NAME@$SERVER_VERSION" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "🧪 **Dry run completed successfully!**" >> $GITHUB_STEP_SUMMARY
            echo "No packages were actually published." >> $GITHUB_STEP_SUMMARY
          fi
